version: '3.7'

services:
    database:
        image: postgres
        container_name: myquiz_database
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=kleidson
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=myquiz
        volumes:
            - pgdata:/data/postgres
    app:
        build: .
        container_name: myquiz
        ports:
            - 3333:3333
        volumes:
            - .:/usr/app
        links:
            - database
        depends_on:
            - database

volumes:
    pgdata:
        driver: local